### ISSUE TITLE
能否集成个 Bounldmaster?

### ISSUE THREAD

**Issue by iamnewaplayer** [ALEXTANGXIAO/TEngine#1]
热更dll 和 素材

**Comment by ALEXTANGXIAO** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ALEXTANGXIAO** [comment]
您好 我还没有用过Bounldmaster，但是如果是热更dll和素材的话服务端可以用oss，客户端打包、下载ab和dll功能接下来我会制作的
