### ISSUE TITLE
资源代码热更新配置文档

### ISSUE THREAD

**Issue by todaystudy** [ALEXTANGXIAO/TEngine#13]
如何把打包好的ab资源包和代码，配置到服务器上面呢。有教程吗

**Comment by ALEXTANGXIAO** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ysj018** [comment]
+1 热更的流程没看太明白 求大佬们指教

**Comment by ALEXTANGXIAO** [comment]
文档已补充~
