### ISSUE TITLE
QQ群群号是不是错了呀？

### ISSUE THREAD

**Issue by zhangbo0403** [ALEXTANGXIAO/TEngine#15]
QQ群群号是不是错了呀？搜索不到啊

**Comment by ALEXTANGXIAO** [comment]
qq群之前莫名其妙违规了，然后群没了

**Comment by huangyan2021** [comment]
再建个一个吧 大佬

**Comment by LanSaber940950797** [comment]
大佬，新群号有吗

**Comment by ALEXTANGXIAO** [comment]
已经建群了，仓库主页最下方

**Comment by itismyera** [comment]
进群问题的答案是啥？咋回答都不对

**Comment by ALEXTANGXIAO** [comment]
![image](https://github.com/ALEXTANGXIAO/TEngine/assets/45391272/646a61c2-8f17-4489-8fde-c7e0bf0c7f21)
