### ISSUE TITLE
PuertsMgr的脚本丢失

### ISSUE THREAD

**Issue by LIES-Chen** [ALEXTANGXIAO/TEngine#17]
在2.0.0版本中的TEngine.prefab内包含一个PuertsMgr，该物体的脚本是丢失状态，，在项目未找到类似名字的脚本文件，请问该PuertsMgr是有什么特殊作用吗？或是可以删除。

**Comment by ALEXTANGXIAO** [comment]
可以删除，近期我会进行修复。
