### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by easyboy3** [ALEXTANGXIAO/TEngine#19]
报错2个：
DirectoryNotFoundException: Could not find a part of the path "C:\UnityTest\TEngine-main\Assets\StreamingAssets\TEngine\AssetBundles\AssetBundleMeta.bin".

[TLogger][ERROR][2023-04-09 20:39:10 953] - Can not find procedure type 'TEngine.Runtime.ProcedureRunPuerts'.

**Comment by qq33357486** [comment]
也是遇到了同样的问题，坐等大佬解答。
另文档里入手就继承：TEngine.TEngine。但命名空间TEngine里没有Tengine类了。

**Comment by ALEXTANGXIAO** [comment]
可以取消ProcedureRunPuerts这个流程的勾选，为之前定制遗留的Puerts热更新流程。另外文档有些旧了 近期我会抽时间更新。
