### ISSUE TITLE
运行UIDemo时候报错

### ISSUE THREAD

**Issue by easyboy3** [ALEXTANGXIAO/TEngine#38]
”DirectoryNotFoundException: Could not find a part of the path "C:\UnityTest\TEngine-main\Assets\StreamingAssets\TEngine\AssetBundles\AssetBundleMeta.bin".
没有文件夹“StreamingAssets" 猜想是否要手动HybirdCLR 打包一次，（需要本地build一次apk，build的时候报错：“Exception: Unity.IL2CPP.Building.BuilderFailedException: Lump_libil2cpp_vm.cpp
C:\UnityTest\TEngine-main\HybridCLRData\LocalIl2CppData-WindowsEditor\il2cpp\libil2cpp\utils/Il2CppHashMap.h(71): error C2039: "hash_compare": ���� "stdext" �ĳ�Ա
”）参考HybirdCLR常见错误，没有找到sparseconfig.h文件添加定义#define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS
然后就进行不下去了

**Comment by ALEXTANGXIAO** [comment]
这应该是两个问题，第一个需要打包切换到编辑器模式就不会走AssetBundleMeta.bin。用最新版本的没有问题，资源模块已经换成了YooAssets，HybridCLR全平台也跑通了
