### ISSUE TITLE
老哥~现在是3.0了，之前文档是不是只是1.0的，已经完全不一样了？

### ISSUE THREAD

**Issue by RenFrog-Gamer** [ALEXTANGXIAO/TEngine#41]
老哥你的框架很棒，整体看下来收获很大，但是发现和链接的文档好像版本差异很大，要是有稍微对照的Example就更好啦~

**Comment by ALEXTANGXIAO** [comment]
你好，链接的文档是有挺长时间没更新了，这个月开发内容比较多，预计6月份会进行最新的补充和更新

**Comment by RenFrog-Gamer** [comment]
> 

谢谢老哥的分享，一起加油~

**Comment by ALEXTANGXIAO** [comment]
最新文档和Demo以及Demo分支已补充~
