### ISSUE TITLE
3.0的网络部分，求大佬能整理一下！

### ISSUE THREAD

**Issue by ysj018** [ALEXTANGXIAO/TEngine#42]
现在看3.0的网络协议部分跑不通，可能是我太菜的问题 希望大佬早日能把这部分整理出来，跑通个登录 我学习一下 TAT~

**Comment by ALEXTANGXIAO** [comment]
你好，3.0的网络还未写完，目前框架差多语言和网络这两个部分，网络协议正处于重构涉及阶段，近期开发任务较重，网络部分预计六月份完工。

**Comment by ysj018** [comment]
打搅大佬！感恩大佬回复！那我就继续蹲一下~

**Comment by ALEXTANGXIAO** [comment]
感谢支持~

**Comment by zero16832** [comment]
TServer不维护了么

**Comment by ALEXTANGXIAO** [comment]
https://github.com/ALEXTANGXIAO/GameNetty
