### ISSUE TITLE
GMBehaviourSystem生命周期问题

### ISSUE THREAD

**Issue by whl160118** [ALEXTANGXIAO/TEngine#45]
![image](https://github.com/ALEXTANGXIAO/TEngine/assets/16745827/c298119a-90dd-4897-98d8-661099d4e4be)
![image](https://github.com/ALEXTANGXIAO/TEngine/assets/16745827/338ce1ed-0f29-4727-af7b-5461b84ed802)
Update周期一帧会执行两次

**Comment by ALEXTANGXIAO** [comment]
感谢提醒，修改已同步
