### ISSUE TITLE
macos中文乱码

### ISSUE THREAD

**Issue by cuilichen** [ALEXTANGXIAO/TEngine#51]
使用macos打开工程后，代码里的中文都是乱码。希望能在工程中把源文件的编码格式改成UTF-8的，这样对使用苹果设备的人更友好。

**Comment by ALEXTANGXIAO** [comment]
你好，可以提供说一下哪些源文件不是UTF-8的格式么？我方便检查一下。我用的是Rider编辑器应该默认保存都是UTF-8格式的。
