### ISSUE TITLE
AudioAgent类中_audioModuleImp的赋值问题

### ISSUE THREAD

**Issue by yangsanhan** [ALEXTANGXIAO/TEngine#54]
![QQ截图20231029182111](https://github.com/ALEXTANGXIAO/TEngine/assets/55923359/8cf7f04b-2e04-41fa-b951-33f9c4f965ca)
![QQ截图20231029182146](https://github.com/ALEXTANGXIAO/TEngine/assets/55923359/77584225-eb95-46c6-b087-ce67fdfa2635)
您好,我发现_audioModuleImp字段只在AudioAgent的Create方法中进行了赋值,但在AudioCategory的构造方法中使用的是默认构造,因此在AudioCategory构造中创建的AudioAgent的_audioModuleImp字段都没有被赋值

**Comment by ALEXTANGXIAO** [comment]
好的，感谢issue，主线已修复。
