### ISSUE TITLE
LoopListView和LoopGridView重复加载问题

### ISSUE THREAD

**Issue by AlanWeekend** [ALEXTANGXIAO/TEngine#60]
LoopListView和LoopGridView会重复调用SetItemData。https://github.com/ALEXTANGXIAO/TEngine/pull/56
上一次pr注释了一部分逻辑。不会重复调用了，但新的数据个数小于原数据个数时不会触发SetItemData。
这块比较复杂，我这边用fancyscrollview实现了。fancyscrollview和uiwidget不太好做兼容，就不提pr了

**Comment by gumcstronger** [comment]
> LoopListView和LoopGridView会重复调用SetItemData。#56 上一次pr注释了一部分逻辑。不会重复调用了，但新的数据个数小于原数据个数时不会触发SetItemData。 这块比较复杂，我这边用fancyscrollview实现了。fancyscrollview和uiwidget不太好做兼容，就不提pr了

你使用UILoopListWidget时有没有遇到GetItem中获取不到数据，我看UILoopListWidget的m_items并没有任何地方调用到，而UIBase中var item = GetItem(preIndex) as IListSelectItem;肯定是null，所以item.SetSelected()永远不会调用到。这是bug么，还是我的使用姿势不对
