### ISSUE TITLE
安卓真机的首包下载完毕后会卡在main场景不执行热更层代码，需要后台退出一次重新进入才正常

### ISSUE THREAD

**Issue by SaberArtoriaFan** [ALEXTANGXIAO/TEngine#61]
还有就是真机联网下载资源包速度较慢合理吗，90M要近十分钟，测试了一下不是手机网速或者服务器传输速度的问题。

**Comment by ALEXTANGXIAO** [comment]
我们有项目在线上跑实测是OK的，包括下载资源包的速度（本身资源框架对下载速度无任何限制），检查一下LoadAssembly的Procedure流程，可以加一些日志打印。或者提供一下最小复现工程。

**Comment by SaberArtoriaFan** [comment]
> 我们有项目在线上跑实测是OK的，包括下载资源包的速度（本身资源框架对下载速度无任何限制），检查一下LoadAssembly的Procedure流程，可以加一些日志打印。或者提供一下最小复现工程。
好的，选择直接build将首包打入apk中似乎一切都正常了
