### ISSUE TITLE
debugger适配问题

### ISSUE THREAD

**Issue by whl160118** [ALEXTANGXIAO/TEngine#66]
RT：竖屏debugger会被遮挡一部分。
![image](https://github.com/ALEXTANGXIAO/TEngine/assets/16745827/fd6060a6-d5f9-460b-9b6f-c5ed27fd4915)

**Comment by ALEXTANGXIAO** [comment]
可以设置宽度，或者设置缩放以适配竖屏。

**Comment by whl160118** [comment]
能根据当前分辨率自动适配宽高吗 我看Next就可以
