### ISSUE TITLE
“文档快速入门”链接挂了

### ISSUE THREAD

**Issue by zhaige95** [ALEXTANGXIAO/TEngine#68]
![Snipaste_2024-05-07_09-14-35](https://github.com/ALEXTANGXIAO/TEngine/assets/41580731/24991af4-9f3e-44d5-ba21-a2e391b2fb77)
![5BDEACC21B268B625D06A7B19C1995D7](https://github.com/ALEXTANGXIAO/TEngine/assets/41580731/3948a9a6-3f0b-4b1d-9898-c79a9f773a3a)

**Comment by ALEXTANGXIAO** [comment]
服务器停了，看下面的快速预览即可，两边内容一致的

**Comment by zhaige95** [comment]
🆗
