### ISSUE TITLE
大佬2.0什么时候能搞完，我打算fork你的改成addressable资源管理的，顺便把热更部分写下

### ISSUE THREAD

**Issue by lcf8858** [ALEXTANGXIAO/TEngine#7]

**Comment by ALEXTANGXIAO** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ALEXTANGXIAO** [comment]
你可以开始写了，目前已经稳定。主要是增加demo和文档，有反馈问题则修复。还有等hybirdClr的package版本发布～

**Comment by Bian-Sh** [comment]
> 你可以开始写了，目前已经稳定。主要是增加demo和文档，有反馈问题则修复。还有等hybirdClr的package版本发布～
hybrid clr upm 版本发布了哦，现在是预览版
