### ISSUE TITLE
这样写的目的是啥，用倒序删除是否也可以实现？

### ISSUE THREAD

**Issue by gsm958708323** [ALEXTANGXIAO/TEngine#74]
这样写的目的是啥，用倒序删除是否也可以实现？

![image](https://github.com/ALEXTANGXIAO/TEngine/assets/29498846/300de06a-8a0c-4d9c-943d-e2b98cb64ae2)

**Comment by gsm958708323** [comment]
发现逻辑bug，最后一个元素赋值到当前位置，移除的当前元素list[i]，那相当于把最后一个元素移除掉了？？？

**Comment by ALEXTANGXIAO** [comment]
这块没有任何 bug，线上验证且优化过。请仔细梳理清楚，倒序移除也能实现，但是整个数组会往前移，性能并不是最优解。

**Comment by gsm958708323** [comment]
不应该是先Release再赋值吗🤔
```
EventRegInfo.Release(listListener[i]);
listListener[i] = listListener[^1];
listListener.RemoveAt(listListener.Count - 1);
```

**Comment by ALEXTANGXIAO** [comment]
之前没做池化。现在池化后Release回收的确实有问题，这里确实应该这样写。

**Comment by Keeyuu** [comment]
> 不应该是先Release再赋值吗🤔
> 
> ```
> EventRegInfo.Release(listListener[i]);
> listListener[i] = listListener[^1];
> listListener.RemoveAt(listListener.Count - 1);
> ```

同问,如果按照  
> ```  
//(假如原先a,b,c) i =1
list[i] = list[^1]; 
//(a,c,c)
EventRegInfo.Release(list[^1]);
//(a,c,null)
list.RemoveAt(list.Count - 1);
//(a,c)
//确实把b删除了,但是b没有触发Release
> ```

**Comment by Keeyuu** [comment]
> 不应该是先Release再赋值吗🤔
> 
> ```
> EventRegInfo.Release(listListener[i]);
> listListener[i] = listListener[^1];
> listListener.RemoveAt(listListener.Count - 1);
> ```

同问

**Comment by ALEXTANGXIAO** [comment]
已经修过了
