### ISSUE TITLE
编辑器停止运行时报错：“Assert FailedTengune.TimerModule is null”

### ISSUE THREAD

**Issue by ReWaterSSS** [ALEXTANGXIAO/TEngine#80]
UIWindow调用Hide，延时关闭界面销毁，然后马上停止游戏运行，
这时GameModule调用了Shutdown，ui界面的立即销毁被调用，但它访问了已经销毁的GameModule.Timer，于是报null了。

![65B4D4D85601EAE683CEF8710AB5EF01](https://github.com/ALEXTANGXIAO/TEngine/assets/66005980/6012d393-131a-4708-9974-4392b6a71733)

**Comment by kenkinky** [comment]
+1

**Comment by ALEXTANGXIAO** [comment]
Fiexd
