### ISSUE TITLE
资源加载的问题

### ISSUE THREAD

**Issue by 15910897938** [ALEXTANGXIAO/TEngine#94]
这个地方先加载一个对象，没有加载完， 新的任务加载同一个任务进来了，就会在tryWaitingLoading 等待，然后 取消第一个任务的CancelToken 打断，就会return  没有删除_assetLoading 中的任务，这就会出现 第二个任务一直在等待超时完成（而且是编辑器下），然后才会处理第二个任务。
![F4S(`9KQSD6@SP{ZJC%9_SS](https://github.com/user-attachments/assets/f1ce9ca6-f0f8-476e-90b6-0c277a3288e5)
![U6J9T3X6%B2PH{D)0XLJ(E1](https://github.com/user-attachments/assets/76e6eec5-2c3c-41b6-89d3-93ae08a7f423)

**Comment by 15910897938** [comment]
这样就是说 加载对象的方法不能被打断。我现在就写成了 不打断，然后逻辑打断了 就把实例化的对象删除 。 是我用的方法不对吗

**Comment by ALEXTANGXIAO** [comment]
已修复
